### ISSUE TITLE
New MyEval Nonsense....

### ISSUE THREAD

**Issue by Welle417** [Jukari2003/Bullet-Blender#2]
They apparently changed the bullet length in myEval and limited it to 115 characters now?!? Short spacing is also going the way of the dodo..

You tool is also presently getting me through a full EPR rewrite, because they changed our approved acronyms and abbreviations and told us to dial it back on the comm jargon... **sigh**

If you get a chance to update the bullet length, please do, or add options for 1206 vs 910 vs myEval...

Bullet Blender rocks my socks.

**Comment by Jukari2003** [comment]
I've just updated it... Although I was just going to let the project die since we are supposed to move to narrative next year. That being said, it will quickly cleanse any EPRs with half-spaces already in them. It should automatically revert to MyEval system, however if you need/want to switch back to "Classic" mode, you just need to select that mode in System Settings.

Enjoy, let me know if you run into anymore issues.
